### ISSUE TITLE
Nosetest / unittest runner for Vows test class

### ISSUE THREAD

**Issue by fatuhoku** [heynemann/pyvows#99]
Various Python tools such as PyCharm have integration with well-established unit-test frameworks in Python that can be triggered with a simple key-combination.

PyVows expects its users to only ever use the command line runner provided, and that is all they will get!

**Comment by coreypobrien** [comment]
A quick check on pycharm makes it look like they build custom code for every framework they support (e.g. unittest, nose, lettuce). That custom support involves custom java to handle configuration (http://goo.gl/GYAyjm) and a custom python script to collect and execute the tests (http://goo.gl/mn8jFL). 

I'm going to go ahead and close this since to really solve the problem someone would need to do one of the following:
1. make an entirely new project called pycharm-pyvows-plugin (assuming there is a way to add custom frameworks via a plugin in pycharm) or, 
2. add a new feature request in the pycharm project titled "Add support for pyvows test runner"
